name: project-contatos

services:
  backend:
    build: 
      context: backend
      target: dev
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    container_name: contatos-backend
    volumes:
      - ./backend:/usr/src/app
      - backend_node_modules:/usr/src/app/node_modules
    ports:
      - "${SERVERPORT}:${SERVERPORT}"
    environment:
      - SERVERPORT=${SERVERPORT}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    entrypoint: npm run start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVERPORT}"]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    build: 
      context: frontend
      target: dev
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend
    container_name: contatos-frontend
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "${WEBPORT}:${WEBPORT}"
    environment:
      - WEBPORT=${WEBPORT}
    entrypoint: npm run dev

  database:
    image: postgres:12.2
    container_name: contatos-database
    ports:
      - "${DBPORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  backend_node_modules:
  frontend_node_modules:
